name: Continuous Integration
on: [push]
jobs:
  build:

    strategy:
      matrix:
        # configuration: [Debug, Release]
        configuration: [Release]

    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    env:
      Solution_Name: AutoGrid.sln
      Test_Project_Path: AutoGrid.Tests/AutoGrid.Tests.csproj
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    # - name: Install .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.101
    
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    # Execute all unit tests in the solution
    # - name: Execute unit tests
    #   run: dotnet test $env:Test_Project_Path

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    # - name: Restore the application
    #   run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
    #   env:
    #     Configuration: ${{ matrix.configuration }}